/**
 * Free-text search over the public lists.
 *
 * Two problems make a naive `contains` the wrong answer here, and both are
 * solved in the same place.
 *
 * **Accents.** Nobody types `José Guimarães` into a search box; they type
 * `jose guimaraes`. An `ILIKE '%jose%'` against the stored name finds nothing,
 * which reads to the citizen as "this person is not on Votto".
 *
 * **Fields, plural.** A name lives in two columns (`firstName`, `lastName`), so
 * `silva junior` matches neither one on its own; a bill is findable by its
 * official title, by the plain-language title the AI wrote, or by its official
 * code, which is three columns.
 *
 * Both are answered by a **`searchText` column** on `Theme`, `PublicAgent` and
 * `Party`: the searchable fields of the row, concatenated, lowercased and
 * stripped of accents. It is a Postgres `GENERATED ... STORED` column — the
 * definition lives in `docs/migrations/0010_search.sql` and nowhere else, so no
 * write path can forget to maintain it and it cannot drift. A GIN trigram index
 * over it is what makes the `LIKE '%…%'` an index scan rather than a table scan.
 *
 * {@link fold} below is the JavaScript mirror of that SQL expression, applied to
 * the *query* so the two sides meet. Changing one without the other silently
 * breaks matching, so they are changed together.
 */
import type { Prisma } from "@/generated/prisma";

/** Most tokens a single query may contribute; beyond this the tail is ignored. */
const MAX_TOKENS = 6;
/** Longest token kept, so one pasted paragraph cannot become a giant pattern. */
const MAX_TOKEN_LENGTH = 40;

/**
 * Normalize a string for comparison: no case, no accents, single spaces.
 *
 * The exact mirror of the SQL behind `searchText`
 * (`translate(lower(…), 'áàâãäå…', 'aaaaaa…')`). `%`, `_` and `\` are dropped
 * because Prisma passes a `contains` value straight into a `LIKE` pattern
 * without escaping them — a lone `%` would otherwise match every row.
 */
export function fold(value: string): string {
  return value
    .normalize("NFD")
    .replace(/\p{Diacritic}/gu, "")
    .toLowerCase()
    .replace(/[%_\\]/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

/**
 * Split a raw query into the tokens every match must contain.
 *
 * Tokens are ANDed by the callers, not ORed: typing more words has to narrow
 * the list, which is the only behaviour that makes a search box feel like it is
 * listening. `joao pt` is "someone called João, in the PT" — not "everything
 * called João plus the whole PT bench".
 *
 * Returns an empty array for an absent or blank query, which callers read as
 * "no search was made" rather than "nothing matched".
 */
export function searchTokens(raw: string | null | undefined): string[] {
  if (!raw) return [];
  return fold(raw)
    .split(" ")
    .filter(Boolean)
    .slice(0, MAX_TOKENS)
    .map((token) => token.slice(0, MAX_TOKEN_LENGTH));
}

/**
 * Search fragment for the agents list: every token must appear in the agent's
 * own name **or** in their party's name/acronym.
 *
 * The party is reached through the relation rather than copied into the agent's
 * `searchText`, because a generated column can only see its own row — and doing
 * it this way means a party rename needs no cascade: `Party.searchText` is
 * regenerated by Postgres and every agent's search follows immediately.
 *
 * Returns `null` when there is nothing to search for, so the caller can leave
 * its `where` untouched.
 */
export function agentSearchFilter(raw: string | null | undefined): Prisma.PublicAgentWhereInput[] | null {
  const tokens = searchTokens(raw);
  if (tokens.length === 0) return null;
  return tokens.map((token) => ({
    OR: [
      { searchText: { contains: token } },
      { party: { searchText: { contains: token } } },
    ],
  }));
}

/**
 * Search fragment for the themes list: every token must appear in the bill's
 * official title, in the plain-language title the AI wrote, or in its official
 * code — and nothing else.
 *
 * The summary is deliberately **not** searched. It is a paragraph of official
 * prose in which half the vocabulary of Brazilian legislation appears at least
 * once, so including it returned a page of unrelated bills for almost any word
 * and made the box feel broken. A title and a code are what a citizen actually
 * has in hand.
 */
export function themeSearchFilter(raw: string | null | undefined): Prisma.ThemeWhereInput[] | null {
  const tokens = searchTokens(raw);
  if (tokens.length === 0) return null;
  return tokens.map((token) => ({ searchText: { contains: token } }));
}
